server:
  port: 8000
  servlet:
    context-path: /
spring:
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**
  http:
    encoding:
      force: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100Mb
      max-request-size: 100Mb
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    servlet:
      content-type: text/html
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hibernate?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  messages:
    basename: i18n.login
logging:
  level:
    root: INFO
    com.mjwise: INFO
web:
  file:
    path: D:/data/bim-manage

